openapi: 3.0.1
info:
  title: XMLToJson
  description: API Definition of XMLToJson
  version: 1.0.0
servers:
- url: http://localhost:8290/XMLToJson
paths:
  /:
    post:
      responses:
        default:
          description: Default response
