openapi: 3.0.1
info:
  title: CBRHeaderJSON
  description: API Definition of CBRHeaderJson
  version: 1.0.0
servers:
- url: http://localhost:8290/hbr
paths:
  /:
    post:
      responses:
        default:
          description: Default response
