openapi: 3.0.1
info:
  title: JSONDataMapper
  description: API Definition of JSONDataMapper
  version: 1.0.0
servers:
- url: http://localhost:8290/JSONDataMapper
paths:
  /:
    post:
      responses:
        default:
          description: Default response
