openapi: 3.0.1
info:
  title: PassThrough
  description: API Definition of PassThrough
  version: 1.0.0
servers:
- url: http://localhost:8290/passthrough
paths:
  /:
    post:
      responses:
        default:
          description: Default response
