openapi: 3.0.1
info:
  title: JSONToXML
  description: API Definition of JSONToXML
  version: 1.0.0
servers:
- url: http://localhost:8290/jsontoxml
paths:
  /:
    post:
      responses:
        default:
          description: Default response
