openapi: 3.0.1
info:
  title: CBRPayloadXML
  description: API Definition of CBRPayloadXML
  version: 1.0.0
servers:
- url: http://localhost:8290/CBRPayloadXML
paths:
  /:
    post:
      responses:
        default:
          description: Default response
