openapi: 3.0.1
info:
  title: CBRPayloadJSON
  description: API Definition of CBRPayloadJson
  version: 1.0.0
servers:
- url: http://localhost:8290/cbr
paths:
  /:
    post:
      responses:
        default:
          description: Default response
