openapi: 3.0.1
info:
  title: CBRHeaderXML
  description: API Definition of CBRHeaderXML
  version: 1.0.0
servers:
- url: http://localhost:8290/hbr
paths:
  /:
    post:
      responses:
        default:
          description: Default response
