openapi: 3.0.1
info:
  title: XMLDataMapper
  description: API Definition of XMLDataMapper
  version: 1.0.0
servers:
- url: http://localhost:8290/xmlmapper
paths:
  /:
    post:
      responses:
        default:
          description: Default response
